---
title: "Assignments"
description: |
  I'll post all course assignments here (homework, writing, and the final project).
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Reminder: All assignments should be submitted via [Gradescope](https://www.gradescope.com/courses/303230).**

## Homework

- [Homework 7](https://www.dropbox.com/s/irnlurn07rc2dr1/hw07.pdf?dl=0) - due on Gradescope by Friday, Nov. 5 at 9:40 am.

- [Homework 6](https://www.dropbox.com/s/wi7sygs41ub6s4q/hw06.pdf?dl=0) - due on Gradescope by Monday, Nov. 1 at 9:50 am.

- [Homework 5](https://www.dropbox.com/s/jexi04t8bs1snoc/hw05.pdf?dl=0) - due on Gradescope by Friday, Oct. 22 at 9:40 am.

- [Homework 4](https://www.dropbox.com/s/bf66ep8hs6rqi17/hw04.pdf?dl=0) - due on Gradescope by Friday, Oct. 15 at 9:40 am.

- [Homework 3](https://www.dropbox.com/s/q2jw6f0nbc51swm/hw03.pdf?dl=0) - due on Gradescope by Monday, Oct. 11 at 9:50 am.

- [Homework 2](https://www.dropbox.com/s/x7t1unxqaykaipt/hw02.pdf?dl=0) - due on Gradescope by Friday, Oct. 1 at 9:40 am.

- [Homework 1](https://www.dropbox.com/s/23whuwbniibehhw/hw01.pdf?dl=0) - due on Gradescope by Friday, Sept. 24 at 9:40 am.

- [Probability review](https://www.dropbox.com/s/k1o96mpyqfe3agc/hw0-prob-review.pdf?dl=0) (not due)

## Writing assignments

- [Writing assignment 2](https://www.dropbox.com/s/7qbimt4fd5dyy27/02-posterior-conclusions.pdf?dl=0) - Draft due Oct 22, Final due Oct 25
    + [writing2-sleep-time-draws.csv](https://aloy.github.io/stat340-notes-fa21/data/writing2-sleep-time-draws.csv)

- [Writing assignment 1](https://www.dropbox.com/s/8o5xinuv0cnwp13/01-prior-tuning.pdf?dl=0)

## Final project

[Final project assignment](https://www.dropbox.com/s/gmpblq5r9rddj70/f2021-final-project.pdf?dl=0)

*Timeline:*

1.  Friday, 5 Nov. Confirm groups. Fill out this Google form (only one group member needs to do this): <https://forms.gle/QEwJoAfoxroPtrGx6>.

2.  Monday, 11 Nov. Submit your proposed data set and a brief proposal by 4 p.m. Your proposal should describe the general topic/phenomenon you want to study, as well some focused questions that you hope to answer and specific hypotheses that you intend to assess. You should also provide an overview of your data set and how it links to your goals. Be sure to clearly communicate the source of your data set.

3.  Tuesday, 23 Nov. Final project due by 8:30 a.m. Submit a .pdf version of your paper on Gradescope and email supplemental materials to me including. The supplemental materials include: (1) your data (in a .csv or .rds file), (2) your code supplement (in a .Rmd or .R file). Your code supplement should be organized and clearly commented. If for some reason your data file is too large, feel free to share it via Dropbox or Google Drive.

4.  Tuesday, 23 Nov. Final project due by 8:30 a.m. Complete the assessment of your contribution to the project and that of your group by midnight. The link to this Google form will be posted on on this site. Completion of this assessment (if you worked in a group) as well as your collaborative effort are specifications of the assignment, so are required.





## Problem topic correspondence

Abbreviation: H1Q1 = Homework 1, Q1

#### Module 1

Problem Topic | Homework problem(s)
------|-------------------
1  | H1Q3, H1Q3, H1Q4, H1Q5, H2Q1, H2Q2, H2Q4, H3Q1
2  | H1Q1, H1Q3, H1Q4, H1Q5, H2Q1, H2Q2, H2Q3, H2Q5, H3Q2, H3Q3
3  | H1Q1, H1Q2, H1Q5, H2Q3, H3Q3
4  | H1Q2, H2Q4
5  | H2Q2, H2Q4, H3Q2, H3Q3

#### Module 2

Abbreviation: WSOct4 = Worksheet from October 4

Problem Topic | Homework problem(s)
------|-------------------
6  |H6Q1   
7  | H3Q4$^\dagger$, H4Q1$^\dagger$, H4Q2$^\dagger$, WSOct4
8  | H4Q1$^*$, H4Q2$^*$, H4Q3$^*$, H4Q4$^*$, WSOct11, WSOct13
9  | H5Q1, H5Q2, H5Q3, WSOct15
10 | H4Q1, H4Q2, WSOct13, H6Q2, H6Q3, H6Q4
11 | H3Q4, H4Q4, H5Q1, H5Q2, H5Q3, WSOct4

$^\dagger=$ when you programmed the log posterior, you had to think about what the posterior was first, so it was a psuedo derivation

$^*=$ if you use the algorithm, then you should be able to explain what it's doing.


#### Module 3

Problem Topic | Homework problem(s)
------|-------------------
12  | H7Q2, H7Q5, H7Q6
13  | H7Q1, H7Q2, H7Q5, H7Q6  
14  | H7Q3, H7Q4, H7Q5, H7Q6  
15  | 
16  | 
17  | 
18  |
