---
title: "Week 09: Regression"
description: |
  This week we'll start exploring regression from the Bayesian perspective.
date: 2021-11-08
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Monday, 08 Nov

### Announcements

Exam 3 is Wednesday, November 17

There is a stats talk Wednesday, November 10 at 4:30 in Anderson


### Topics

- Wrap up hierarchical beta-binomial modeling

- Intro to Bayesian regression

### Materials

- [Hierarchical beta-binomial model slides](https://aloy.github.io/stat340-notes-fa21/19-hierarchical-beta-binom.pdf)

- [Intro to Bayesian regression](https://aloy.github.io/stat340-notes-fa21/20-slr.pdf)

- [Collaborative notes](https://docs.google.com/document/d/17fLwlp7Smn_rB9wGdyoMB3eJaqLvmcEr1vt0Kq8N-Rs/edit?usp=sharing)

### Before next time

1. Work on homework 8

1. Read sections 11.7-11.9


## Wednesday, 03 Nov

### Topics

- Fitting simple linear regression

- Informative priors (one method)


### Materials


- [SLR in JAGS slides](https://aloy.github.io/stat340-notes-fa21/21-slr-jags.pdf) (wrapping up hierarchical normal models)

- [Your turn .Rmd](https://aloy.github.io/stat340-notes-fa21/21H-slr-jags.html)

- [Your turn solution](https://aloy.github.io/stat340-notes-fa21/21H-soln-slr-jags.pdf)


- [Collaborative notes](https://docs.google.com/document/d/101ABxa86_1C-P000JQhK2-MZCPScow01Ug7bV-QyuF4/edit?usp=sharing)


### Before next time

1. Finish homework 8



## Friday, 05 Nov

### Announcements

- Homework 8 is due today by 9:40 am

- I will post homework 9 soon

- Exam 3 is on Wednesday

### Topics

- Another approach to informative priors

- Model diagnostics

- Writing workshop

### Materials



[SLR model checking](https://aloy.github.io/stat340-notes-fa21/22-slr-checking.pdf)

[Model checking R code handout](https://aloy.github.io/stat340-notes-fa21/22H-slr-checking.html)

<!-- [Collaborative notes](https://docs.google.com/document/d/1IVN2c1UKpvL9IUrg6RDpN2xahv3owD7GieycYruHBL4/edit?usp=sharing) -->



### Before next time

1. Start homework 9

<!-- 1. Read sections 11.1-11.6 -->



