---
title: "Week 08: Hierarchical models"
description: |
  This week, we'll keep exploring hierarchical Bayesian models.
date: 2021-11-01
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Monday, 01 Nov


### Topics

Hierarchical normal modeling

### Materials

- [Hiearchichal normal slides](https://aloy.github.io/stat340-notes-fa21/18-hierarchical-normal2.pdf) (these start on slide 25 from Friday)

- [Collaborative notes](https://docs.google.com/document/d/1tY5mZJaIPMv9sit6U4wTdVbHMIchMwKs0yhr_79tSOY/edit?usp=sharing)

### Before next time

1. Work on homework 7


## Wednesday, 03 Nov

### Topics

- Posterior prediction

- Pointers on hyperprior for between group variance

- Hierarchical beta-binomial modeling

### Materials

- [Hiearchichal normal slides](https://aloy.github.io/stat340-notes-fa21/18-hierarchical-normal2.pdf) (wrapping up hierarchical normal models)

    + [Gelman's wiki on prior distributions](https://github.com/stan-dev/stan/wiki/Prior-Choice-Recommendations) - a lot of good information, not all is relevant to this course

    + Optional reading on priors for between group variance: [Gelman (2004)](http://www.stat.columbia.edu/~gelman/research/published/taumain.pdf)

- [Hierarchical beta-binomial model slides](https://aloy.github.io/stat340-notes-fa21/19-hierarchical-beta-binom.pdf)



### Before next time

1. Read Section 10.3

1. Finish homework 7



## Friday, 05 Nov

### Announcements

- Homework 7 is due today by 9:40 am

- I will post homework 8 soon

### Topics

Hierarchical beta-binomial modeling


### Materials

[Hierarchical beta-binomial model slides](https://aloy.github.io/stat340-notes-fa21/19-hierarchical-beta-binom.pdf)



### Before next time

1. Start homework 8

1. Read sections 11.1-11.6


