---
title: "Week 01: Welcome to Bayesian statistics!"
description: |
  This week we'll review some key results from probability and start discussing
  Bayesian inference for a proportion.
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Wednesday, 15 Sept

### Announcements

Welcome!

If you want to have copies of the slides, then please print and bring them to class.

### Topics/activities

[Slides](https://aloy.github.io/stat340-notes-fa21/01-probability-review.pdf)

- Welcome
- What is specs grading?
- Probability review

### Before next time

- Please [sign up for two collaborative note slots ](https://docs.google.com/document/d/1-RjAbLxBAxEuy0R4HrMSHMwoNs0XilKwwT5cGBGswvM/edit?usp=sharing)

- Work on [probability review problems](https://www.dropbox.com/s/k1o96mpyqfe3agc/hw0-prob-review.pdf?dl=0) (not due), review key topics as needed. 

- Once you have given the problems an honest effort, you can look at the [solutions](https://www.dropbox.com/s/twtchey7aujhrvx/00-Probability-review.pdf?dl=0).

- Review probability topics as needed

    + Here are all of the [recordings from my Fall 2020 probability class](https://carleton.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=2088b73f-581c-40e9-818f-ac23012a9103) to help you review.

    + Some former students have also found [Joe Blitzstein's probability lectures](https://projects.iq.harvard.edu/stat110/youtube) helpful.

- Read sections 7.1-7.2

- Please install the software/R packages outlined on the [Course resources page](https://aloy.github.io/stat340/resources.html). Let me know if you hit any snags.

## Friday, 17 Sept

### Announcements

Homework 1 is due by 8:30 a.m. on Friday, September 24.

### Topics/activities

[Slides](https://aloy.github.io/stat340-notes-fa21/02-prop-discrete-prior.pdf)

[R code](https://aloy.github.io/stat340/code/02H-discrete-prior-r.html)

[Collaborative notes](https://docs.google.com/document/d/1JrWib_6Tkrct4BB2FESZ0mNvLrXydcnSXv7Pug1Nqjw/edit?usp=sharing)

- Inference for a proportion with discrete priors



### Before next time

1. Read sections 7.3-7.5

2. Start homework 1
