---
title: "Week 02: Univariate inference"
description: |
  This week we'll discuss how to use continuous priors and make predictions 
  for proportions. We'll also discuss how to use prior information to select prior distributions.
preview: densities.png
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Monday, 20 Sept

### Topics

- Inference with continuous priors

### Materials

[Slides](https://aloy.github.io/stat340-notes-fa21/03-prop-continuous-prior.pdf)

[Your turns](https://aloy.github.io/stat340-notes-fa21/03H-posterior-examples) (you can copy and paste code from here) 

[Collaborative notes](https://docs.google.com/document/d/1hqi2f3YOLiJ7OVtRGa9TWrkF0sW-Mku4mA2kNc9tpSQ/edit?usp=sharing)





### Before next time

1. Review section 7.3.2, read section 7.6

1. Work on homework 1



## Wednesday, 22 Sept

### Topics

- Predicting a new observation

- Choosing informative priors

### Materials

We'll wrap up Monday's slides, and then look at these [slides](https://aloy.github.io/stat340-notes-fa21/04-prior-elicitation.pdf) on prior elicitation

[Your turns](https://aloy.github.io/stat340-notes-fa21/04H-prior-elicitation.pdf)

[.Rmd file for your turns](https://aloy.github.io/stat340-notes-fa21/04H-prior-elicitation.Rmd)

[Collaborative notes](https://docs.google.com/document/d/1hxxIdmDbJxphO1YEpr255HuUDCTMvfTEGXIcq-or5t8/edit?usp=sharing)


### Before next time


1. Finish homework 1 and upload to Gradescope before Friday's class

## Friday, 24 Sept

### Announcements

Homework 1 is due by 9:40 am

I will post Homework 2 today

### Topics

- Prior predictive checking

- Sensitivity analysis

- Weak/vauge priors

- Posterior predictive checks

### Materials

[Slides](https://aloy.github.io/stat340-notes-fa21/05-weak-priors.pdf) (We'll wrap up Wednesday's slides first, and then look at these)


### Before next time

1. Read sections 8.1-8.5. We won't discuss the discrete priors in section 8.3 much in class, but it will help you build your understanding as your read. 

2. Start homework 2




